services:
  - type: web
    name: sport-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn web_api:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: ODDS_API_KEY
        sync: false
