LEAGUE_ZH = {
    "NBA": "美國職籃",
    "MLB": "美國職棒",
    "英超": "英格蘭超級聯賽",
    "西甲": "西班牙甲級聯賽",
    "德甲": "德國甲級聯賽",
    "歐洲國家盃": "歐洲國家盃",
    "世界盃": "FIFA 世界盃",
}

TEAM_ZH = {
    # NBA
    "San Antonio Spurs": "聖安東尼奧馬刺",
    "New York Knicks": "紐約尼克",
    "Los Angeles Lakers": "洛杉磯湖人",
    "Boston Celtics": "波士頓塞爾提克",
    "Golden State Warriors": "金州勇士",
    "Denver Nuggets": "丹佛金塊",
    "Miami Heat": "邁阿密熱火",
    "Chicago Bulls": "芝加哥公牛",
    "Dallas Mavericks": "達拉斯獨行俠",
    "Phoenix Suns": "鳳凰城太陽",
    "Milwaukee Bucks": "密爾瓦基公鹿",
    "Philadelphia 76ers": "費城七六人",
    "Brooklyn Nets": "布魯克林籃網",
    "Cleveland Cavaliers": "克里夫蘭騎士",
    "Memphis Grizzlies": "曼菲斯灰熊",
    "Minnesota Timberwolves": "明尼蘇達灰狼",
    "Oklahoma City Thunder": "奧克拉荷馬雷霆",
    "Indiana Pacers": "印第安納溜馬",
    "Orlando Magic": "奧蘭多魔術",
    "Atlanta Hawks": "亞特蘭大老鷹",
    "Toronto Raptors": "多倫多暴龍",
    "Houston Rockets": "休士頓火箭",
    "Utah Jazz": "猶他爵士",
    "Portland Trail Blazers": "波特蘭拓荒者",
    "Sacramento Kings": "沙加緬度國王",
    "Los Angeles Clippers": "洛杉磯快艇",
    "Detroit Pistons": "底特律活塞",
    "Washington Wizards": "華盛頓巫師",
    "Charlotte Hornets": "夏洛特黃蜂",
    "New Orleans Pelicans": "紐奧良鵜鶘",
    # MLB
    "Chicago Cubs": "芝加哥小熊",
    "San Francisco Giants": "舊金山巨人",
    "Philadelphia Phillies": "費城費城人",
    "Chicago White Sox": "芝加哥白襪",
    "Detroit Tigers": "底特律老虎",
    "Seattle Mariners": "西雅圖水手",
    "New York Yankees": "紐約洋基",
    "Boston Red Sox": "波士頓紅襪",
    "Toronto Blue Jays": "多倫多藍鳥",
    "Baltimore Orioles": "巴爾的摩金鶯",
    "Miami Marlins": "邁阿密馬林魚",
    "Tampa Bay Rays": "坦帕灣光芒",
    "Los Angeles Dodgers": "洛杉磯道奇",
    "St. Louis Cardinals": "聖路易紅雀",
    "St Louis Cardinals": "聖路易紅雀",
    "Atlanta Braves": "亞特蘭大勇士",
    "Houston Astros": "休士頓太空人",
    "Texas Rangers": "德州遊騎兵",
    "Cleveland Guardians": "克里夫蘭守護者",
    "Minnesota Twins": "明尼蘇達雙城",
    "Kansas City Royals": "堪薩斯市皇家",
    "Oakland Athletics": "奧克蘭運動家",
    "Athletics": "奧克蘭運動家",
    "Los Angeles Angels": "洛杉磯天使",
    "San Diego Padres": "聖地牙哥教士",
    "Arizona Diamondbacks": "亞利桑那響尾蛇",
    "Colorado Rockies": "科羅拉多落磯",
    "Cincinnati Reds": "辛辛那提紅人",
    "Pittsburgh Pirates": "匹茲堡海盜",
    "Milwaukee Brewers": "密爾瓦基釀酒人",
    "Washington Nationals": "華盛頓國民",
    "New York Mets": "紐約大都會",
    # 足球常見
    "Manchester City": "曼城",
    "Arsenal": "兵工廠",
    "Liverpool": "利物浦",
    "Chelsea": "切爾西",
    "Manchester United": "曼聯",
    "Tottenham Hotspur": "熱刺",
    "Real Madrid": "皇家馬德里",
    "Barcelona": "巴塞隆納",
    "Bayern Munich": "拜仁慕尼黑",
    "Borussia Dortmund": "多特蒙德",
    "Brazil": "巴西",
    "France": "法國",
    "Argentina": "阿根廷",
    "Germany": "德國",
    # 世界盃常見
    "Mexico": "墨西哥",
    "South Africa": "南非",
    "United States": "美國",
    "USA": "美國",
    "England": "英格蘭",
    "Spain": "西班牙",
    "Italy": "義大利",
    "Portugal": "葡萄牙",
    "Netherlands": "荷蘭",
    "Belgium": "比利時",
    "Croatia": "克羅埃西亞",
    "Japan": "日本",
    "South Korea": "南韓",
    "Korea Republic": "南韓",
    "Australia": "澳洲",
    "Saudi Arabia": "沙烏地阿拉伯",
    "Canada": "加拿大",
    "Switzerland": "瑞士",
    "Poland": "波蘭",
    "Denmark": "丹麥",
    "Sweden": "瑞典",
    "Uruguay": "烏拉圭",
    "Colombia": "哥倫比亞",
    "Chile": "智利",
    "Ecuador": "厄瓜多",
    "Peru": "秘魯",
    "Paraguay": "巴拉圭",
    "Morocco": "摩洛哥",
    "Senegal": "塞內加爾",
    "Nigeria": "奈及利亞",
    "Ghana": "迦納",
    "Cameroon": "喀麥隆",
    "Tunisia": "突尼西亞",
    "Iran": "伊朗",
    "Qatar": "卡達",
    "Costa Rica": "哥斯大黎加",
    "Serbia": "塞爾維亞",
    "Wales": "威爾斯",
    "Scotland": "蘇格蘭",
}


def to_zh_team(name: str) -> str:
    if not name:
        return "未知隊伍"
    return TEAM_ZH.get(name, name)


def to_zh_league(name: str) -> str:
    if not name:
        return "未知聯盟"
    return LEAGUE_ZH.get(name, name)
